# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) (Clip? ${{ matrix.config.allow_clip }} Type? ${{ matrix.config.clip_type }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest, r: "release", allow_clip: TRUE }
          - { os: windows-latest, r: "release", allow_clip: TRUE }
          - { os: windows-latest, r: "devel", allow_clip: TRUE }
          - {
              os: ubuntu-latest,
              r: "devel",
              http-user-agent: "release",
              allow_clip: TRUE,
              clip_type: xclip,
            }
          - {
              os: ubuntu-latest,
              r: "release",
              allow_clip: TRUE,
              clip_type: xclip,
            }
          - {
              os: ubuntu-latest,
              r: "release",
              allow_clip: TRUE,
              clip_type: xsel,
            }
          - { os: ubuntu-latest, r: "release", clip_type: xsel }
          - {
              os: ubuntu-latest,
              r: "release",
              allow_clip: TRUE,
              clip_type: none,
            }
          - {
              os: ubuntu-latest,
              r: "release",
              allow_clip: TRUE,
              clip_type: nodisplay,
            }
          - {
              os: ubuntu-latest,
              r: "oldrel-1",
              allow_clip: TRUE,
              clip_type: xclip,
            }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - name: Install and run XVFB
        if: ${{ matrix.config.clip_type == 'xclip' || matrix.config.clip_type == 'xsel' }}
        run: |
          sudo apt-get install -y xvfb
          sudo /usr/bin/Xvfb :99.0 -screen 0 1280x1024x24 &
          sleep 3

      - name: Install xclip
        if: ${{ matrix.config.clip_type == 'xclip' }}
        run: |
          sudo apt-get install -y xclip
          # Initialize xclip
          uptime | xclip -i -sel p -f | xclip -i -sel c
          xclip -o -sel clipboard
        env:
          DISPLAY: ":99.0"

      - name: Install xclip (nodisplay)
        if: ${{ matrix.config.clip_type == 'nodisplay' }}
        run: |
          sudo apt-get install -y xclip

      - name: Install xsel
        if: ${{ matrix.config.clip_type == 'xsel' }}
        run: |
          sudo apt-get install -y xsel

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ matrix.config.clip_type != 'nodisplay' }}
        env:
          ALLOW_CLIP: ${{ matrix.config.allow_clip }}
          CLIP_TYPE: ${{ matrix.config.clip_type }}
          DISPLAY: ":99.0"
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ matrix.config.clip_type == 'nodisplay' }}
        env:
          ALLOW_CLIP: ${{ matrix.config.allow_clip }}
          CLIP_TYPE: ${{ matrix.config.clip_type }}
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
